# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zGOPMUocScpP0f0wYzWMGy4qVL69fYdv
"""

# src/config.py

PROJECT_DIR = "/content/drive/MyDrive/Praktikum/quantum_kernel_gpr_framework"

SAVE_MODE = "scratch"

SCRATCH_FILE = f"{PROJECT_DIR}/experiments_scratch.parquet"
FINAL_FILE = f"{PROJECT_DIR}/experiments_final.parquet"