# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUwsWcMb9vcjOuw1aNiuy4ftGPe7mKzZ
"""

import torch


def func(x):
    return torch.sin(torch.pi * x)

def make_sine_data(n_points=30, noise=0.1):
    X = torch.rand(n_points) * 2 - 1
    y = func(X) + noise * torch.randn_like(X)
    return X, y

'''
def func(x, mu=0.0, sigma=0.3):
    return torch.exp(-((x - mu) ** 2) / (2 * sigma ** 2))

def make_gaussian_data(n_points=30, noise=0.1):
    X = torch.rand(n_points) * 2 - 1  # Uniformly sample in [-1, 1]
    y = func(X) + noise * torch.randn_like(X)
    return X, y
'''