# -*- coding: utf-8 -*-
"""logger.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d8T-8tPMjlkdOI3pAqobBYwqvcMTeR1Q
"""

# src/logger.py

from datetime import datetime
import torch
import os
import pandas as pd


# ======================================================
# PARQUET APPENDER
# ======================================================

def append_parquet(row, parquet_file):

    new_df = pd.DataFrame([row])

    if os.path.exists(parquet_file):
        old_df = pd.read_parquet(parquet_file)
        combined_df = pd.concat([old_df, new_df], ignore_index=True)
    else:
        combined_df = new_df

    combined_df.to_parquet(parquet_file, index=False)


# ======================================================
# BUILD ROW
# ======================================================

def build_experiment_row(
    n_qubits,
    n_layers,
    kernel,
    lr,
    epochs,
    N_train,
    N_test,
    noise_eps,
    phi,
    mse,
    runtime_sec,
    likelihood,
    losses,
    initial_params,
    seed=22
):

    return {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),

        "n_qubits": n_qubits,
        "n_layers": n_layers,
        "n_params": kernel.n_params,

        "learning_rate": lr,
        "epochs": epochs,

        "N_train": N_train,
        "N_test": N_test,

        "noise_eps": noise_eps,

        "phi": str(phi.__name__) if hasattr(phi, "__name__") else str(phi),

        "mse": float(mse),

        "runtime_sec": runtime_sec,

        "likelihood_noise": float(likelihood.noise.item()),

        "final_loss": float(losses[-1]),

        "parameter_movement": float(
            torch.norm(kernel.params.detach() - initial_params).item()
        ),

        "seed": seed
    }


# ======================================================
# SAVE RESULT
# ======================================================

def save_experiment(row, save_mode, scratch_file, final_file):

    if save_mode == "scratch":
        append_parquet(row, scratch_file)
        print("Saved to scratch database")

    elif save_mode == "final":
        append_parquet(row, final_file)
        print("Saved to final database")

    else:
        raise ValueError(f"Unknown SAVE_MODE: {save_mode}")