# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iDQmEhn3XnwO8wMryzWU6MOUohAjFlD_
"""

import torch
import gpytorch
import pennylane as qml

class QGP(gpytorch.models.ExactGP): #define QGP through classical GP from pytorch
#wo hier y benutzt
    def __init__(self, train_x, train_y, likelihood, kernel): #If the class has an __init__, Python automatically executes it.
        super(QGP, self).__init__(train_x, train_y, likelihood) #könnte es was anderes als die likelihood sein?
        #super: initialize everything from base model first, run the initializer of the parent class using these arguments.
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = kernel

    def forward(self, x): #forward() describes the GP prior/posterior distribution for inputs x
        mean_x = self.mean_module(x) #defined it now use it on x
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x) #gaussian process distribution