# -*- coding: utf-8 -*-
"""plotting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZtnV7K0lVX-zLfjJz8ezw0rsAyBUpoKp
"""

# src/plotting.py

import matplotlib.pyplot as plt
import torch
import seaborn as sns
from cycler import cycler


# ======================================================
# GLOBAL STYLE (optional but recommended)
# ======================================================

def set_plot_style():
    plt.rcParams.update({
        "axes.prop_cycle": cycler('color', sns.color_palette("viridis", 5)),
        "figure.figsize": (5.0, 4.0),

        "font.family": "serif",
        "font.size": 15,

        "axes.labelsize": 20,
        "xtick.labelsize": 15,
        "ytick.labelsize": 15,
        "legend.fontsize": 15,

        "text.usetex": True,
        "mathtext.fontset": "dejavuserif",
        "text.latex.preamble": r"\usepackage{amsmath} \usepackage{amssymb}",

        "axes.linewidth": 0.6,

        "lines.linewidth": 2.5,

        "axes.spines.top": True,
        "axes.spines.right": True,

        "xtick.direction": "in",
        "ytick.direction": "in",

        "xtick.minor.visible": True,
        "ytick.minor.visible": True,

        "grid.alpha": 0.3,

        "legend.frameon": False,

        "savefig.bbox": "tight",
        "savefig.pad_inches": 0.05,
        "savefig.dpi": 300,
    })


# ======================================================
# 1. LOSS PLOT
# ======================================================

def plot_loss(losses, save_path=None):
    plt.figure()
    plt.plot(losses)
    plt.xlabel("Iteration")
    plt.ylabel("Loss")
    plt.title("Training Loss")
    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=300)

    plt.show()


# ======================================================
# 2. KERNEL MATRIX VISUALIZATION
# ======================================================

def plot_kernel_matrix(K, title="Kernel Matrix", save_path=None):
    plt.figure()
    plt.imshow(K.detach().cpu().numpy(), aspect="auto")
    plt.colorbar()
    plt.title(title)

    if save_path:
        plt.savefig(save_path, dpi=300)

    plt.show()


# ======================================================
# 3. REGRESSION RESULT (MAIN PLOT)
# ======================================================

def plot_regression(
    X_train,
    y_train,
    X_test,
    y_test,
    pred_mean,
    pred_var,
    save_path=None
):

    X_train = X_train.detach().cpu()
    y_train = y_train.detach().cpu()

    X_test = X_test.detach().cpu()
    y_test = y_test.detach().cpu()

    mean = pred_mean.detach().cpu()
    std = torch.sqrt(pred_var.detach().cpu())

    lower = mean - std
    upper = mean + std

    fig, ax = plt.subplots(figsize=(5.0, 4.0))

    ax.plot(
        X_train.numpy(),
        y_train.numpy(),
        "k.",
        label="Samples",
        markersize=8.0
    )

    ax.plot(
        X_test.numpy(),
        mean.numpy(),
        label="Mean"
    )

    ax.plot(
        X_test.numpy(),
        y_test.numpy(),
        color="k",
        label="True"
    )

    ax.fill_between(
        X_test.numpy(),
        lower.numpy(),
        upper.numpy(),
        alpha=0.3,
        label="Variance"
    )

    ax.plot(
        X_test.numpy(),
        lower.numpy(),
        "k--",
        linewidth=1.5
    )

    ax.plot(
        X_test.numpy(),
        upper.numpy(),
        "k--",
        linewidth=1.5
    )

    ax.set_xlim([-1.0, 1.0])
    ax.set_ylim([-1.5, 1.5])

    ax.set_xlabel(r'$\mathbf{x}$')
    ax.set_ylabel(r'$f(\mathbf{x})$')

    ax.legend(loc="best")
    ax.grid()

    plt.tight_layout()

    if save_path:
        plt.savefig(save_path)

    plt.show()


# ======================================================
# 4. PREDICTION UNCERTAINTY ONLY (OPTIONAL DEBUG TOOL)
# ======================================================

def plot_uncertainty(X, mean, var):
    X = X.detach().cpu()
    mean = mean.detach().cpu()
    std = torch.sqrt(var.detach().cpu())

    plt.figure()
    plt.plot(X, mean, label="Mean")
    plt.fill_between(
        X.numpy(),
        (mean - std).numpy(),
        (mean + std).numpy(),
        alpha=0.3
    )
    plt.legend()
    plt.title("Uncertainty")
    plt.show()


# ======================================================
# 5. PARAMETER / DIAGNOSTIC PLOTS (OPTIONAL)
# ======================================================

def plot_losses_and_gradients(losses, grad_norms=None):
    plt.figure()
    plt.plot(losses, label="Loss")

    if grad_norms is not None:
        plt.plot(grad_norms, label="Grad norm")

    plt.legend()
    plt.title("Training Diagnostics")
    plt.show()

