# -*- coding: utf-8 -*-
"""quantum_kernel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12amEHUp7iiTDCUM_TjYZgpBfniGGA3Kd
"""

import torch
import gpytorch
import pennylane as qml

class QuantumKernel(gpytorch.kernels.Kernel):
    def __init__(self, n_qubits, n_layers, phi, **kwargs): #constructor
        super(QuantumKernel, self).__init__(**kwargs) #calls the constructor of the parent class? checke nicht ganz

        # Anzahl der Qubits, und Layers, für den Quantum Circuit
        self.n_qubits = n_qubits
        self.n_layers = n_layers
        self.phi = phi

        # Hier werden die trainierbaren Parameter initialisiert. Der Parameter
        # self.n_params gibt an, wie viele trainierbare Parameter der Circuit
        # überhaupt hat. Es könnte sein, dass du den Parameter manuell ändern
        # musst, falls du mal einen anderen Circuit ausprobierst.
        self.n_params = self.n_qubits * (self.n_layers + 1) #habe ich es hier richtig gemacht?
        self.params = torch.nn.Parameter(2 * torch.pi * torch.rand(self.n_params)) #trainable parameter in pytorch

        # Man muss immer erstmal ein Quantum Device initialisieren. Wenn wir
        # einen richtigen Quantum Computer benutzen würden, dann müsste man hier
        # den entsprechenden Quantum Computer verknüpfen. Da wir aber nur
        # Simulationen durchführen, benutzen wir einfach "default.qubit". Das
        # ist das Standard-Device von PennyLane für Quantensimulationen
        self.dev = qml.device("default.qubit", wires=self.n_qubits) #define quantum device, default?
        self.quantum_kernel_circuit = qml.QNode(self._circuit_definition, self.dev, interface='torch') #circuit definition kommt woher?

    def feature_map(self, x, params):
        """
        Das ist eigentlich der Kern des ganzen. Hier ist unsere Feature Map oder
        Quantum Circuit Architecture definiert. Wir haben hier einige rotation
        gates (RY, RX) und wir haben auch entangling gates (CRZ). Unser x, also
        unser Datenpunkt wird im self.phi(x) encoded. Und der params Vektor
        beinhaltet die trainierbaren Parameter, die wir meistens theta nennen
        """
        '''
        pairs = [(i, (i + 1) % self.n_qubits) for i in range(self.n_qubits)] #checke die loop nicht ganz
        for i in range(self.n_qubits):
            qml.RY(params[i], wires=i) #wires?
        for j in range(self.n_layers):
            for i in range(self.n_qubits): #nicht zuerst durch qbits?
                qml.RX(params[i] * 2.0 * self.phi(x), wires=i)
            for k, (q1, q2) in enumerate(pairs):
                qml.CNOT(wires=[q1, q2]) #CNOT option
        '''
        pairs = [(i, (i + 1) % self.n_qubits) for i in range(self.n_qubits)]
        for i in range(self.n_qubits):
            qml.RY(params[i], wires=i)
        for j in range(self.n_layers):
            for i in range(self.n_qubits):
                qml.RX(params[i] * 2.0 * self.phi(x), wires=i)
            for k, (q1, q2) in enumerate(pairs):
                qml.CRZ(params[self.n_qubits + j * len(pairs) + k], wires=[q1, q2])

    def _circuit_definition(self, x1, x2, params):
        """
        Das ist der Quantum Kernel. Das ist prinizipiell die Implementierung die
        du in der Powerpoint siehst, mit dem U und U^dg. Am Ende returnen wir
        die Probabilities. Da wir drei Qubits benutzen gibt es 2^3 = 8
        verschiedene Zustände. Und die gemessenen Probabilities zeigen dann, wie
        wahrscheinlich es ist, dass wir in einem spezifischen Zustand sind. Das
        könnte dann z.B. so aussehen:

        probs = [0.35, 0.56, 0.01, 0.03, ...]

        Hier wäre z.B. der zweite Zustand am wahrscheinlichsten.

        """
        self.feature_map(x1, params)
        qml.adjoint(self.feature_map)(x2, params)
        return qml.probs(wires=range(self.n_qubits))

    def kernel(self, x1, x2, params):
        """
        Wir benutzen den ersten Wert von den gemessenen Probabilities als
        Kernel-Wert. Also das wäre dann der erste Wert aus probs oben, also 0.35
        """
        probs = self.quantum_kernel_circuit(x1, x2, params)
        return probs[0][0]

    def forward(self, x1, x2, diag=False, **params):
        """
        Hier wird unsere Kernel-Matrix K zusammengestellt. Für jede Komponente
        K(x1, x2) berechnen wir den Wert mit dem Quantum Circuit

        for i in range(len(x1)):
            for j in range(len(x2)):
                kernel_matrix[i, j] = self.kernel(x1[i], x2[j], self.params)
        if diag:
            return kernel_matrix.diag()
        return kernel_matrix
        """
        kernel_matrix = torch.zeros((len(x1), len(x2)))

        square_matrix = len(x1) == len(x2)

        for i in range(len(x1)):

            if square_matrix:
                kernel_matrix[i, i] = 1.0
                start_j = i + 1
            else:
                start_j = 0

            for j in range(start_j, len(x2)):

                val = self.kernel(x1[i], x2[j], self.params)

                kernel_matrix[i, j] = val

                if square_matrix:
                    kernel_matrix[j, i] = val
        return kernel_matrix